### ISSUE TITLE
Enable travis testing

### ISSUE THREAD

**Issue by hexylena** [martenson/public-galaxy-servers#17]
I've already configured the .travis.yml @martenson! :)

**Comment by martenson** [comment]
I will close the issue then :D

**Comment by hexylena** [comment]
No, as in I've written the test cases. If you could go here and flip the switch. https://travis-ci.org/martenson/public-galaxy-servers

**Comment by martenson** [comment]
yay clicking buttons!

**Comment by martenson** [comment]
trigerred build https://travis-ci.org/martenson/public-galaxy-servers/builds/290563848

**Comment by hexylena** [comment]
Perfect! thanks so much
